let rawData = [
  {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
     {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Emerald Mansion, New York",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
   {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "hospitality",
  },
   {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "institutional",
  },
     {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "institutional",
  },
     {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "institutional",
  },
   {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Haven, Sydney",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Opal Oasis, Rio de Janeiro",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Quartz Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
   {
    year: 2016,
    name: "Quartz Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Pearl Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
    {
    year: 2016,
    name: "Pearl Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Jade Junction, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
    {
    year: 2016,
    name: "Jade Junction, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Citrine Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  
   {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "commercial",
  },
   {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "residential",
  },
    {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "residential"
  },
   {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "hospitality",
  },
   {
    year: 2016,
    name: "Amethyst Alley, Rome",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img4.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Azure Apartments, Madrid",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img2.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Amethyst Alley, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Azure Apartments, Madrid",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Diamond Mall, Shanghai",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Granite Library, Sydney",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Crystal Cafe, Paris",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Quartz Residences, New York",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Gold Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Marble Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Apartments, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Sapphire Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Opal Office, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
    {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
      {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Emerald Mansion, New York",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Haven, Sydney",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Opal Oasis, Rio de Janeiro",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Quartz Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Pearl Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Jade Junction, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Citrine Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Amethyst Alley, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Azure Apartments, Madrid",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Diamond Mall, Shanghai",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Granite Library, Sydney",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Crystal Cafe, Paris",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Quartz Residences, New York",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Gold Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Marble Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Apartments, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.png",
    type: "residential",
  },
  {
    year: 2016,
    name: "Sapphire Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.png",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
   {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "commercial",
  },
   {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "architecture",
  },
   {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "institutional",
  },
   {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "commercial",
  },
   {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "architecture",
  },
   {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.png",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Opal Office, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.png",
    type: "hospitality",
  },
];
let swiperData = [
  {
    name: "Suchitra JY",
    content:
      "Working with Deepa Suriyaprakash and the Betweenlines team has been a joyful home-creation experience for me. Right from my first meeting with Deepa, when I was exploring options for two home interior projects, I got excellent vibes and instinctively I knew that I had got the right person. Deepa gets the essence of what you are trying to achieve with every single corner of the house and executes it beautifully. No idea that you throw at her is discarded without being given due consideration. However outlandish our scheme, she always heard us out and gave us her view on it with details of technical and financial feasability, and practical pros and cons. I would gladly take another journey with this team should the opportunity arise in the future. Deepa came up with excellent ideas on how to integrate many of our existing pieces into a new domain, and thanks to that we are happily in a new place that will always be reminiscent of our past.",
    by: "House of relics, Bengaluru",
  },
  {
    name: "Suchitra JY",
    content:
      "Working with Deepa Suriyaprakash and the Betweenlines team has been a joyful home-creation experience for me. Right from my first meeting with Deepa, when I was exploring options for two home interior projects, I got excellent vibes and instinctively I knew that I had got the right person. Deepa gets the essence of what you are trying to achieve with every single corner of the house and executes it beautifully. No idea that you throw at her is discarded without being given due consideration. However outlandish our scheme, she always heard us out and gave us her view on it with details of technical and financial feasability, and practical pros and cons. I would gladly take another journey with this team should the opportunity arise in the future. Deepa came up with excellent ideas on how to integrate many of our existing pieces into a new domain, and thanks to that we are happily in a new place that will always be reminiscent of our past.",
    by: "House of relics, Bengaluru",
  },
  {
    name: "Suchitra JY",
    content:
      "Working with Deepa Suriyaprakash and the Betweenlines team has been a joyful home-creation experience for me. Right from my first meeting with Deepa, when I was exploring options for two home interior projects, I got excellent vibes and instinctively I knew that I had got the right person. Deepa gets the essence of what you are trying to achieve with every single corner of the house and executes it beautifully. No idea that you throw at her is discarded without being given due consideration. However outlandish our scheme, she always heard us out and gave us her view on it with details of technical and financial feasability, and practical pros and cons. I would gladly take another journey with this team should the opportunity arise in the future. Deepa came up with excellent ideas on how to integrate many of our existing pieces into a new domain, and thanks to that we are happily in a new place that will always be reminiscent of our past.",
    by: "House of relics, Bengaluru",
  },
  {
    name: "Suchitra JY",
    content:
      "Working with Deepa Suriyaprakash and the Betweenlines team has been a joyful home-creation experience for me. Right from my first meeting with Deepa, when I was exploring options for two home interior projects, I got excellent vibes and instinctively I knew that I had got the right person. Deepa gets the essence of what you are trying to achieve with every single corner of the house and executes it beautifully. No idea that you throw at her is discarded without being given due consideration. However outlandish our scheme, she always heard us out and gave us her view on it with details of technical and financial feasability, and practical pros and cons. I would gladly take another journey with this team should the opportunity arise in the future. Deepa came up with excellent ideas on how to integrate many of our existing pieces into a new domain, and thanks to that we are happily in a new place that will always be reminiscent of our past.",
    by: "House of relics, Bengaluru",
  },
  {
    name: "Suchitra JY",
    content:
      "Working with Deepa Suriyaprakash and the Betweenlines team has been a joyful home-creation experience for me. Right from my first meeting with Deepa, when I was exploring options for two home interior projects, I got excellent vibes and instinctively I knew that I had got the right person. Deepa gets the essence of what you are trying to achieve with every single corner of the house and executes it beautifully. No idea that you throw at her is discarded without being given due consideration. However outlandish our scheme, she always heard us out and gave us her view on it with details of technical and financial feasability, and practical pros and cons. I would gladly take another journey with this team should the opportunity arise in the future. Deepa came up with excellent ideas on how to integrate many of our existing pieces into a new domain, and thanks to that we are happily in a new place that will always be reminiscent of our past.",
    by: "House of relics, Bengaluru",
  },
];
let runningText = [
  "Nalli",
  "Raasi Builders",
  "Co-optex",
  "TNHDC",
  "Navgati",
  "Nandakumar Law Associates",
  "Hands of India",
  "HSBC",
  "Techno Orbit",
  "Rang De",
];
